### ISSUE TITLE
Tag 0.1.1 : unexpected error error_class=NoMethodError error="undefined method `add'

### ISSUE THREAD

**Issue by lduriez** [nttcom/fluent-plugin-rabbitmq#23]
Hello,

Since I upgrade fluent-plugin-rabbitmq from 0.1.0 to 0.1.1 I have the following error : 
```
  2023-11-22 16:58:42 +0100 [error]: #0 unexpected error error_class=NoMethodError error="undefined method `add' for #<Fluent::PluginLogger:0x00007ff1c1b4b800>"
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/transport.rb:374:in `log_peer_certificate_info'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/transport.rb:93:in `connect'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/bunny-2.14.4/lib/bunny/session.rb:317:in `start'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluent-plugin-rabbitmq-0.1.1/lib/fluent/plugin/out_rabbitmq.rb:125:in `start'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:203:in `block in start'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:192:in `block (2 levels) in lifecycle'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:191:in `each'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:191:in `block in lifecycle'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:178:in `each'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:178:in `lifecycle'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/root_agent.rb:202:in `start'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/engine.rb:248:in `start'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/engine.rb:147:in `run'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/supervisor.rb:617:in `block in run_worker'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/supervisor.rb:962:in `main_process'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/supervisor.rb:608:in `run_worker'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/lib/fluent/command/fluentd.rb:372:in `<top (required)>'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:83:in `require'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/lib/ruby/gems/2.7.0/gems/fluentd-1.16.2/bin/fluentd:15:in `<top (required)>'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/bin/fluentd:23:in `load'
  2023-11-22 16:58:43 +0100 [error]: #0 /opt/td-agent/bin/fluentd:23:in `<main>'
```

I don't know what change from your side, and if I'm alone getting that issue.
I thought it's related to this commit but I'm not sure about it : <https://github.com/nttcom/fluent-plugin-rabbitmq/commit/b340314d6da48cefabbc0ec5c5ba7176800f2346>

For information
td-agent version = `td-agent 4.5.1 fluentd 1.16.2 (d5685ada81ac89a35a79965f1e94bbe5952a5d3a)`
system release = `Amazon Linux release 2 (Karoo)`

**Comment by lduriez** [comment]
I forgot to share my conf :
```
<source>
  @type udp
  tag events
  format json
  port 44446
  body_size_limit 1MB
</source>

<match events>
  @id events
  @type rabbitmq
  host rabbitmq.***.***
  port 5671
  user toto
  pass secret
  vhost /events
  exchange server_events
  exchange_type fanout
  exchange_durable true
  content_type application/octet-stream
  tls true
  automatically_recover true
  network_recovery_interval 30
  recovery_attempts 3
  connection_timeout 30
  continuation_timeout 600
  <format>
    @type json
  </format>
</match>
```

**Comment by ODudek** [comment]
It looks like that [this](https://github.com/nttcom/fluent-plugin-rabbitmq/blob/v0.1.1/lib/fluent/plugin/out_rabbitmq.rb#L98) line break the client

**Comment by mmasaki** [comment]
@lduriez Thank you for your report. I fixed this issue in 0.1.2.
